language:
  - python

python:
  - "3.6"
    
matrix:
  include:
    - os: linux
      dist: bionic
      sudo: required

install:
  - sudo apt install cmake ffmpeg libtag1-dev
  - pip3 install pyacoustid pytaglib

script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make
  - ctest --output-on-failure
