language:
  - c

matrix:
  include:
    - os: linux
      dist: bionic
      sudo: required

install:
  - sudo apt install cmake ffmpeg python3-pip
  - pip3 install pyacoustid pytaglib

script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make
  - ctest --output-on-failure
