language:
  - python
 
python:
  - "3.5"

os:
  - linux
  - osx

sudo:
  - true

addons:
  apt:
    packages:
      - cmake
      - mp3info
      - python3-pip
      - libtag1-dev
      - libchromaprint-dev
      - ubuntu-restricted-extras
      - libav-tools

install:
  - pip3 install pyacoustid pytaglib

script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make
  - ctest --output-on-failure

