language:
  - c

matrix:
  include:
    - os: linux
      dist: bionic
      sudo: required

before_install:
  - sudo apt-get install python3 python3-pip cmake ffmpeg libtag1-dev

install:
  - pip3 install pyacoustid pytaglib

script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make
  - ctest --output-on-failure
