language:
  - python

python:
  - "3.6"
    
matrix:
  include:
    - os: linux
      dist: bionic
      sudo: required

addons:
  apt:
    packages:
      - cmake
      - ffmpeg
      - libtag1-dev

install:
  - pip3 install pyacoustid pytaglib

script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make
  - ctest --output-on-failure
