language:
  - c

os:
  - linux

sudo:
  - true

addons:
  apt:
    packages:
      - cmake
      - libav-tools
      - python3-pip
      - libtag1-dev

install:
  - sudo pip3 install pyacoustid pytaglib

script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make
  - ctest --output-on-failure
